services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: aww
      POSTGRES_PASSWORD: awwpassword
      POSTGRES_DB: awwdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
