name: CI — Build CMS & Web (pnpm workspace)

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

jobs:
  node-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20 (with pnpm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: |
            code/apps/web/pnpm-lock.yaml
            code/apps/cms/pnpm-lock.yaml

      - name: Enable Corepack & activate pnpm 10.18.2
        run: |
          corepack enable
          corepack prepare pnpm@10.18.2 --activate
          pnpm --version
          which pnpm

      # --- CMS ---
      - name: Install deps (cms)
        working-directory: ./code/apps/cms
        run: pnpm install --frozen-lockfile

      - name: Typecheck (cms, optional)
        working-directory: ./code/apps/cms
        run: pnpm run typecheck --if-present

      - name: Lint (cms, optional)
        working-directory: ./code/apps/cms
        run: pnpm run lint --if-present

      - name: Build (cms)
        working-directory: ./code/apps/cms
        run: pnpm run build

      # --- WEB ---
      - name: Install deps (web)
        working-directory: ./code/apps/web
        run: pnpm install --frozen-lockfile

      - name: Typecheck (web, optional)
        working-directory: ./code/apps/web
        run: pnpm run typecheck --if-present

      - name: Lint (web, optional)
        working-directory: ./code/apps/web
        run: pnpm run lint --if-present

      - name: Build (web)
        working-directory: ./code/apps/web
        run: pnpm run build

  compose-validate:
    runs-on: ubuntu-latest
    needs: node-build
    defaults:
      run:
        working-directory: ./code/infra

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate docker compose config
        run: docker compose config

      - name: Pull referenced images
        run: docker compose pull --ignore-pull-failures

      - name: Build local images (if any)
        run: docker compose build --pull