name: CI — Build CMS & Web (minimal, official pnpm order)

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

jobs:
  node-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: |
            code/apps/web/pnpm-lock.yaml
            code/apps/cms/pnpm-lock.yaml

      - name: Sanity check tools
        run: |
          node -v
          pnpm -v
          which pnpm

      # --- CMS (install + build) ---
      - name: Install deps (cms)
        working-directory: ./code/apps/cms
        run: pnpm install --frozen-lockfile

      - name: Build (cms)
        working-directory: ./code/apps/cms
        run: pnpm run build

      # --- WEB (install + build) ---
      - name: Install deps (web)
        working-directory: ./code/apps/web
        run: pnpm install --frozen-lockfile

      - name: Build (web)
        working-directory: ./code/apps/web
        run: pnpm run build

  compose-validate:
    runs-on: ubuntu-latest
    needs: node-build
    defaults:
      run:
        working-directory: ./code/infra

    steps:
      - uses: actions/checkout@v4

      - name: Validate docker compose config
        run: docker compose config

      - name: Pull referenced images
        run: docker compose pull --ignore-pull-failures

      - name: Build local images (if any)
        run: docker compose build --pull